/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SQRT_H_RPCGEN
#define _SQRT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define SQRTPROG 199
#define SQRTVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define sqrt 1
extern  float * sqrt_1(int *, CLIENT *);
//extern  float * sqrt_1_svc(int *, struct svc_req *);
extern int sqrtprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sqrt 1
extern  float * sqrt_1();
//extern  float * sqrt_1_svc();
extern int sqrtprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SQRT_H_RPCGEN */
