#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <gmp.h>
#include  "sqrt.h"				/* msg.h generated by rpcgen */

float *sqrt_1(int *opn, CLIENT *req)
{
    float res = 5.0f;
    return &res;
}
