;sg
;c:\emu8086\inc\0_com_template.txt
org 100h

DATA SEGMENT WORD PUBLIC
    INPUT DW 2093h,2324h,2351h,0023h;
    OUTPUT DB 4 DUP(0);
    SCALE DB 09h;
    BAD_DIV_FLAG DB 00h ;
DATA ENDS  

STACK_SEG SEGMENT 
    DW 100 DUP(0);
    TOP LABEL WORD;
STACK_SEG ENDS   
;NOW EXPORT THE BAD_DIV_FLAG
PUBLIC BAD_DIV_FLAG ;

INT_PROC SEGMENT WORD PUBLIC 
    EXTRN BAD_DIV:FAR
INT_PROC ENDS

CODE SEGMENT WORD PUBLIC 
    ASSUME CS:CODE,DS:DATA,SS:STACK_SEG
START: 
    MOV AX,STACK_SEG ;
    MOV SS,AX         ; init ss
    MOV AX,DATA       ; 
    MOV DS,AX         ; init ds
    LEA SP,TOP        ; init sp
   ;A TYPE ZERO INTERRUPT WILL MOVE TO 00000h to find
   ;The Service routine's address,so put the value of our BAD_DIV
   ;ROUTINE THERE
   MOV AX,0000h
   MOV ES,AX
   ;;SETTING THE VECTOR TABLE
   MOV WORD PTR ES:0002h,SEG BAD_DIV
   MOV WORD PTR ES:0000h,OFFSET BAD_DIV
   ;;NOW START THE LOOP
   LEA SI,INPUT
   LEA BX,OUTPUT
   MOV CX,0004h
NEXT: 
    MOV AX,[SI]
    DIV SCALE
    CMP BAD_DIV_FLAG,01
    JNE OK              
    
    MOV BYTE PTR [BX],00 ;IF THERE WAS OVERFLOW ,PUT IN 00
    JMP SKIP
 OK:
    MOV BYTE PTR [BX],AL
 SKIP:
    ADD SI,02H ;ADD 2 ,FETCH NEXT WORD
    INC BX     ;PUT TO NEXT BYTE
    MOV BAD_DIV_FLAG,00        
    LOOP NEXT
    END START
    CODE ENDS

      
    

ret




