/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADDER_H_RPCGEN
#define _ADDER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operation {
	char op1[500];
	char op2[500];
	char operator;
};
typedef struct operation operation;

#define ADDERPROG 0x20000003
#define ADDERVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADDER 1
extern  char ** adder_1(operation *, CLIENT *);
extern  char ** adder_1_svc(operation *, struct svc_req *);
extern int adderprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADDER 1
extern  char ** adder_1();
extern  char ** adder_1_svc();
extern int adderprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operation (XDR *, operation*);

#else /* K&R C */
extern bool_t xdr_operation ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADDER_H_RPCGEN */
