#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <gmp.h>
#include  "adder.h"				/* msg.h generated by rpcgen */

char **adder_1(operation *opn, CLIENT *req)
{
    mpz_t n11, n12, n13;
    mpz_init(n11);
    mpz_init(n12);
    mpz_init(n13);
    mpz_set_str(n11, opn->op1, 10);
    mpz_set_str(n12, opn->op2, 10);
    
    FILE *f = fopen("/home/aman/console", "a");
	
    if (f == (FILE *)NULL) {
        return NULL;
	}

    fprintf(f, "op 1 : %s, %s, %c\n", opn->op1, opn->op2, opn->operator);

    switch(opn->operator) {
        case '+':
        mpz_add(n13, n11, n12);
        break;

        case '-':
        mpz_sub(n13, n11, n12);
        break;

        case '*':
        mpz_mul(n13, n11, n12);
        break;

        
        case '/':
        mpz_cdiv_q(n13, n11, n12);
        break;

        default:
        fprintf(f, "Cannot perform operations\n");
        break;
    }
<<<<<<< HEAD

	fclose(f);
=======
    
    static char *result;
    FILE *f = fopen("/home/aman/console.txt", "a");
    if(!f) {
        char *errstr = malloc(100);
        strcpy(errstr, "ERROR OPENING FILE!\0");
        result = errstr;
        return &result;
    }
    fprintf(f, "Operated");
>>>>>>> 3107b1d50fb1a588986fdf71bdbfc8c7c13b274c
    char *str = malloc(1000);
    mpz_get_str(str, 10, n13);
    result = str;
    fclose(f);
    return &result;
}
