/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADDER_H_RPCGEN
#define _ADDER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define ADDERPROG 0x20000003
#define ADDERVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADDER 1
extern  char ** adder_1(char **, CLIENT *);
extern  char ** adder_1_svc(char **, struct svc_req *);
extern int adderprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADDER 1
extern  char ** adder_1();
extern  char ** adder_1_svc();
extern int adderprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADDER_H_RPCGEN */
