#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <gmp.h>
#include  "adder.h"				/* msg.h generated by rpcgen */

char **adder_1(char **b, CLIENT *req)
{
    printf("Solving!");
    char n1[1000], n2[1000];
    mpz_t n11, n12, n13;
    int i, j;
    i = 0;
    j = 0;
    while(isspace(b[0][i])) {
        i++;
    }
    while(isdigit(b[0][i])) {
        n1[j++] = b[0][i++];
    }
    while(isspace(b[0][i])) {
        i++;
    }
    char op = b[0][i];
    i++;
    n1[j] = '\0';
    j = 0;
    while(isspace(b[0][i])) {
        i++;
    }
    while(b[0][i]) {
        n2[j++] = b[0][i++];
    }
    n2[j] = '\0';

    mpz_init(n11);
    mpz_init(n12);
    mpz_init(n13);
    mpz_set_str(n11, n1, 10);
    mpz_set_str(n12, n2, 10);
    switch(op) {
        case '+':
        mpz_add(n13, n11, n12);
        break;
        
        case '-':
        mpz_sub(n13, n11, n12);
        break;

        case '*':
        mpz_mul(n13, n11, n12);
        break;

        
        case '/':
        mpz_cdiv_q(n13, n11, n12);
        break;
    }

    char *str = malloc(1000);
    mpz_get_str(str, 10, n13);
    static char *result;
    result = str;
    return &result;
}
