/*
 * rprintmsg.c: remote version
 * of "printmsg.c"
 */
#include <stdio.h>
#include "adder.h"			/* msg.h generated by rpcgen */
 
main(argc, argv)
	int argc;
	char *argv[];
{
	CLIENT *clnt;
	char *server;
	char *message = malloc(1000);
 
	if (argc != 2) {
		exit(1);
	}
 
	server = argv[1];
    int i = 0;
    while(i < 50) {
    if (fgets(message, 1000, stdin)) {
	/*
	 * Create client "handle" used for 
 * calling MESSAGEPROG on the server
	 * designated on the command line.
	 */
	clnt = clnt_create(server, ADDERPROG,
								ADDERVERS,
								"tcp");
	if (clnt == (CLIENT *)NULL) {
		/*
		 * Couldn't establish connection
    * with server.
		 * Print error message and die.
		 */
		clnt_pcreateerror(server);
		exit(1);
	}
		/*
	 * Call the remote procedure
 * "printmessage" on the server
	 */
    
	char **result = adder_1(&message, clnt);
	printf("> result :  %s\n", *result);
    }      
    }

	clnt_destroy( clnt );
	exit(0);
}
