//sg
/*
 * msg_proc.c: implementation of the
 * remote procedure "printmessage"
 */
#include <stdio.h>
#include <gmp.h>
#include <malloc.h>
#include <stdlib.h>
#include  "adder.h"				/* msg.h generated by rpcgen */

int main(int argc, char **b)
{
    char *n1, n2[1000];
    n1 = malloc(1000);
    mpz_t n11, n12, n13;
    int i, j;
    i = 0;
    j = 0;
    while(isspace(b[1][i])) {
        printf(" i = %d\n", i);
        i++;
    }
    while(isdigit(b[1][i])) {
        printf(" i = %d\n", i);
        n1[j++] = b[1][i++];
    }
    while(isspace(b[1][i])) {
        printf(" i = %d\n", i);
        i++;
    }
    i++; //skip the +
    n1[j] = '\0';
    j = 0;
    while(isspace(b[1][i])) {
        printf(" i = %d\n", i);
        i++;
    }
    while(b[1][i]) {
        printf(" i = %d\n", i);
        n2[j++] = b[1][i++];
    }
    n2[j] = '\0';
    printf("%s and %s\n", n1, n2);
    mpz_init(n12);
    mpz_init(n13);
    mpz_init(n11);
    mpz_set_str(n11, n1, 10);
    mpz_set_str(n12, n2, 10);
    mpz_add(n13, n12, n11);
    char *str = malloc(1000);
    mpz_get_str(str, 10, n13);
    static unsigned long res = 0;
    printf("%s\n", str);
}
