/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "portmapper.h"

bool_t
xdr_pmap (XDR *xdrs, pmap *objp)
{
	register int32_t *buf;

	 if (!xdr_rpcprog_t (xdrs, &objp->prog))
		 return FALSE;
	 if (!xdr_rpcvers_t (xdrs, &objp->vers))
		 return FALSE;
	 if (!xdr_rpcprot_t (xdrs, &objp->prot))
		 return FALSE;
	 if (!xdr_rpcport_t (xdrs, &objp->port))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pmaplist (XDR *xdrs, pmaplist *objp)
{
	register int32_t *buf;

	 if (!xdr_pmap (xdrs, &objp->map))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (pmaplist), (xdrproc_t) xdr_pmaplist))
		 return FALSE;
	return TRUE;
}
