/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PORTMAPPER_H_RPCGEN
#define _PORTMAPPER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define PMAP_PORT 111

struct pmap {
	rpcprog_t prog;
	rpcvers_t vers;
	rpcprot_t prot;
	rpcport_t port;
};
typedef struct pmap pmap;
#define IPPROTO_TCP 6
#define IPPROTO_UDP 17

struct pmaplist {
	pmap map;
	struct pmaplist *next;
};
typedef struct pmaplist pmaplist;

#define PMAP_PROG 100000
#define PMAP_VERS 2

#if defined(__STDC__) || defined(__cplusplus)
#define PMAPPROC_NULL 0
extern  void * pmapproc_null_2(void *, CLIENT *);
extern  void * pmapproc_null_2_svc(void *, struct svc_req *);
#define PMAPPROC_SET 1
extern  bool_t * pmapproc_set_2(pmap *, CLIENT *);
extern  bool_t * pmapproc_set_2_svc(pmap *, struct svc_req *);
#define PMAPPROC_UNSET 2
extern  bool_t * pmapproc_unset_2(pmap *, CLIENT *);
extern  bool_t * pmapproc_unset_2_svc(pmap *, struct svc_req *);
#define PMAPPROC_GETPORT 3
extern  u_int * pmapproc_getport_2(pmap *, CLIENT *);
extern  u_int * pmapproc_getport_2_svc(pmap *, struct svc_req *);
#define PMAPPROC_DUMP 4
extern  pmaplist * pmapproc_dump_2(void *, CLIENT *);
extern  pmaplist * pmapproc_dump_2_svc(void *, struct svc_req *);
extern int pmap_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PMAPPROC_NULL 0
extern  void * pmapproc_null_2();
extern  void * pmapproc_null_2_svc();
#define PMAPPROC_SET 1
extern  bool_t * pmapproc_set_2();
extern  bool_t * pmapproc_set_2_svc();
#define PMAPPROC_UNSET 2
extern  bool_t * pmapproc_unset_2();
extern  bool_t * pmapproc_unset_2_svc();
#define PMAPPROC_GETPORT 3
extern  u_int * pmapproc_getport_2();
extern  u_int * pmapproc_getport_2_svc();
#define PMAPPROC_DUMP 4
extern  pmaplist * pmapproc_dump_2();
extern  pmaplist * pmapproc_dump_2_svc();
extern int pmap_prog_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_pmap (XDR *, pmap*);
extern  bool_t xdr_pmaplist (XDR *, pmaplist*);

#else /* K&R C */
extern bool_t xdr_pmap ();
extern bool_t xdr_pmaplist ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PORTMAPPER_H_RPCGEN */
